/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myproject;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;



/**
 *
 * @author thidapondchuanwiriyachan
 */
public class Frame9 extends javax.swing.JFrame {

    /**
     * Creates new form Frame9
     */
    public Frame9() {
        initComponents();
        addPlaceholderStyle(txtUsername);
        addPlaceholderStyle(txtPassword);
        
    }
    
    public void addPlaceholderStyle(JTextField textField)
    {
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
        
    }
    public void removePlaceholderStyle(JTextField textField)
    {
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnLogin2 = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setText("Username");

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername.setText("Username");
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });

        jLabel3.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogin2.setText("Login");
        btnLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin2ActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtPassword.setText("Password");
        txtPassword.setEchoChar('\u0000');
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        jLabel4.setText("( Doctor )");

        jLabel5.setText("( Personnel )");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLogin2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtPassword))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin2)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myproject/5b3b106d0f00e1f36bdd058536008877.jpg"))); // NOI18N

        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
        if(txtUsername.getText().equals("Username"))
        {
            txtUsername.setText(null);
            txtUsername.requestFocus();
            removePlaceholderStyle(txtUsername);
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:
        if(txtPassword.getText().equals("Password"))
        {
            txtPassword.setText(null);
            txtPassword.requestFocus();
            txtPassword.setEchoChar('*');
            removePlaceholderStyle(txtPassword);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
        if(txtUsername.getText().length()==0)
        {
            addPlaceholderStyle(txtUsername);
            txtUsername.setText("Username");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
        if(txtPassword.getText().equals("Password"))
        {
            txtPassword.setText(null);
            txtPassword.requestFocus();
            txtPassword.setEchoChar('@');
            removePlaceholderStyle(txtPassword);
        }
    }//GEN-LAST:event_txtPasswordFocusLost
int counts = 0; 
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        File file;
        String line = ""; // อ่านจบเก็บที่ line
        String x, y = "";
        try {
            FileReader reader = new FileReader("/Users/thidapondchuanwiriyachan/Downloads/java2/MyProject/Clinic/LogInD.txt");
            BufferedReader bufferedReader = new BufferedReader(reader);
            boolean validLogin = false; // เก็บสถานะvalidLoginให้เป็นเท็จเพื่อไม่ให้เข้าได้ก่อน
            
            //ลูปอ่านข้อมูลและเก็บในตัวแปรlineและหากยังไม่คืนค่าnull(ว่าง)ก็จะอ่านข้อมูลต่อไปเรื่อยๆจนกว่าจะคืนค่าว่างแล้วออกจากลูป
            while ((line = bufferedReader.readLine()) != null) { 
                String[] parts = line.trim().split(" ");
                x = parts[0].trim();
                y = parts[1].trim();

                // ตรวจuserกับรหัส
                if (txtUsername.getText().equals(x) && txtPassword.getText().equals(y)) {
                    validLogin = true; // ตรงกัน จะเปลี่ยนให้validLogin เป็น true
                    break;
                }
            }
            if(validLogin) {
                JOptionPane.showMessageDialog(null, "OK");
            Frame2 fmain = new Frame2(); //linkไปหน้าตาราง
            fmain.setVisible(true);
            this.dispose();//ปิดหน้าต่างเดิม
            }
            else {
            counts++;
            JOptionPane.showMessageDialog(null, "Error " + counts + " times"); txtUsername.setText("");
            txtPassword.setText("");
            txtUsername.requestFocus();
            }
            if(counts >= 3) 
            {
                JOptionPane.showMessageDialog(null, "กรุณาติดต่อผู้ดูแลระบบ");
                System.exit(0); 
            }
        }   
        catch (IOException e) {
            e.printStackTrace();
        }
        
        
        
//        File file; //ประกาศเป็น Public
//        String line =""; //ประกาศเป็น Public
//        String x, y = "";
//    try 
//    {
//        FileReader reader = new FileReader("/Users/thidapondchuanwiriyachan/Downloads/java2/MyProject/Clinic/LogInD.txt");
//        BufferedReader bufferedReader = new BufferedReader(reader); 
//        line = bufferedReader.readLine().toString();
//        reader.close();
//    } 
//    catch (IOException e) 
//    { 
//        e.printStackTrace();
//    }
//        String[] parts = line.trim().split(" ");//เก็บเป็นช่องว่าง เเต่ถ้าเก็บเป็น , ก็ต้องเป็น ,
//        x = parts[0].trim();
//        y = parts[1].trim();
//        if(txtUsername.getText().equals(x) && txtPassword.getText().equals(y))
//        {
//            JOptionPane.showMessageDialog(this, "Welcome");
//            Frame3 fmain =new Frame3(); 
//            fmain.setVisible(true);
//        }
//        
//        else
//        JOptionPane.showMessageDialog(this, "Invalid Login");
//        
        
        //ปิดหน้าต่าง
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin2ActionPerformed
        // TODO add your handling code here:
        
        
        File file;
        String line = ""; // อ่านจบเก็บที่ line
        String x, y = "";
        try {
            FileReader reader = new FileReader("/Users/thidapondchuanwiriyachan/Downloads/java2/MyProject/Clinic/LogInP.txt");
            BufferedReader bufferedReader = new BufferedReader(reader);
            boolean validLogin = false; // เก็บสถานะvalidLoginให้เป็นเท็จเพื่อไม่ให้เข้าได้ก่อน
            
            //ลูปอ่านข้อมูลและเก็บในตัวแปรlineและหากยังไม่คืนค่าnull(ว่าง)ก็จะอ่านข้อมูลต่อไปเรื่อยๆจนกว่าจะคืนค่าว่างแล้วออกจากลูป
            while ((line = bufferedReader.readLine()) != null) { 
                String[] parts = line.trim().split(" ");
                x = parts[0].trim();
                y = parts[1].trim();

                // ตรวจuserกับรหัส
                if (txtUsername.getText().equals(x) && txtPassword.getText().equals(y)) {
                    validLogin = true; // ตรงกัน จะเปลี่ยนให้validLogin เป็น true
                    break;
                }
            }
            if(validLogin) {
                JOptionPane.showMessageDialog(null, "OK");
            Frame3 fmain = new Frame3(); //linkไปหน้าตาราง
            fmain.setVisible(true);
            this.dispose();//ปิดหน้าต่างเดิม
            }
            else {
            counts++;
            JOptionPane.showMessageDialog(null, "Error " + counts + " times"); txtUsername.setText("");
            txtPassword.setText("");
            txtUsername.requestFocus();
            }
            if(counts >= 3) 
            {
                JOptionPane.showMessageDialog(null, "กรุณาติดต่อผู้ดูแลระบบ");
                System.exit(0); 
            }
        }   
        catch (IOException e) {
            e.printStackTrace();
        }
        
        
        
//        File file; //ประกาศเป็น Public
//        String line =""; //ประกาศเป็น Public
//        String x, y = "";
//    try 
//    {
//        FileReader reader = new FileReader("/Users/thidapondchuanwiriyachan/Downloads/java2/MyProject/Clinic/LogInP.txt");
//        BufferedReader bufferedReader = new BufferedReader(reader); 
//        line = bufferedReader.readLine().toString();
//        reader.close();
//    } 
//    catch (IOException e) 
//    { 
//        e.printStackTrace();
//    }
//        String[] parts = line.trim().split(" ");//เก็บเป็นช่องว่าง เเต่ถ้าเก็บเป็น , ก็ต้องเป็น ,
//        x = parts[0].trim();
//        y = parts[1].trim();
//        if(txtUsername.getText().equals(x) && txtPassword.getText().equals(y)) 
//        {
//            JOptionPane.showMessageDialog(this, "Welcome");
//            Frame3 fmain =new Frame3(); 
//            fmain.setVisible(true);
//        }
//        else
//        JOptionPane.showMessageDialog(this, "Invalid Login");
        
        
        
        //ปิดหน้าต่าง
        this.dispose();
    }//GEN-LAST:event_btnLogin2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        //หยุดการทำงานของแอฟทั้งหมด
        if(JOptionPane.showConfirmDialog(rootPane, 
            "Are you sure?","Confiem",JOptionPane.YES_NO_OPTION)==
                JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
